"""initial all model

Revision ID: 6c88d489690c
Revises: 
Create Date: 2026-07-17 15:48:22.371609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c88d489690c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FIRST_ENTRY', 'STREAK_7', 'STREAK_30', 'STREAK_100', 'BUDGET_MASTER', 'ECONOMIST', 'DETECTIVE', 'SNIPER', name='achievementtype', native_enum=False), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('bank_type', sa.Enum('TINKOFF', 'SBER', 'ALFA', 'VTB', 'RAIFFEISEN', 'UNIVERSAL', name='banktype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'CATEGORIZING', 'QUESTIONS_READY', 'DONE', 'FAILED', name='importstatus', native_enum=False), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('auto_categorized', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('freeze_available', sa.Boolean(), nullable=False),
    sa.Column('freeze_used_date', sa.Date(), nullable=True),
    sa.Column('total_active_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vs_prev_week_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('top_categories', sa.JSON(), nullable=True),
    sa.Column('satisfaction', sa.Enum('HAPPY', 'NEUTRAL', 'UNHAPPY', name='satisfaction', native_enum=False), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'CONTAINS', 'REGEX', 'MCC', name='rulematchtype', native_enum=False), nullable=False),
    sa.Column('match_value', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('mcc_code', sa.String(length=4), nullable=True),
    sa.Column('bank_category', sa.String(length=100), nullable=True),
    sa.Column('categorization_method', sa.Enum('AUTO_RULE', 'AUTO_MCC', 'AUTO_MERCHANT', 'AUTO_BANK', 'GUIDED', 'MANUAL', 'UNCATEGORIZED', name='categorizationmethod', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('FILE_IMPORT', 'MANUAL_ENTRY', name='transactionsource', native_enum=False), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['import_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_dedup_hash'), 'transactions', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_name'), 'transactions', ['merchant_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_merchant_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_dedup_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('rules')
    op.drop_table('weekly_reviews')
    op.drop_table('streaks')
    op.drop_table('import_jobs')
    op.drop_table('categories')
    op.drop_table('achievements')
    # ### end Alembic commands ###
